version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - currency-service-network
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - currency-service-network
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - currency-service-network
    restart: always
  
networks:
  currency-service-network:
    external: true
